apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps", "resourcequotas", "persistentvolumeclaims", "namespaces", "serviceaccounts", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["vpcresources.k8s.aws"]
  resources: ["cninodes"]
  verbs: ["get", "list", "watch"]